name: url_encode_string
description: Easily URL encode a string.
author: bwhitehead0
inputs:
  string:
    description: 'The string to encode.'
    required: true
outputs:
  encoded_string:
    description: The URL encoded string.
    value: ${{ steps.get_job_id.outputs.job_id }}
runs:
  using: 'composite'
  steps:
    - name: Encode string
      id: get_encoded_string
      run: ${{ github.action_path }}/assets/encode_string.sh "${{ inputs.string }}"
      shell: bash

branding:
  icon: 'terminal'
  color: 'blue'