on: [push]

jobs:
    bats_test:
      runs-on: ubuntu-latest
      name: Install Bats and bats libs
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
            submodules: true
        - name: Set working directory
          run: cd ${{ github.workspace }}/url_encode_string
        - name: Setup bats and bats libs
          id: setup-bats
          uses: bats-core/bats-action@3.0.0
        - name: Run bats tests
          shell: bash
          env:
            BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
            TERM: xterm
          run: bats test
