name:  ShellCheck Scan
on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Gather runner diagnostic info
        uses: bwhitehead0/runner_info@v1
        with:
          detail-level: full # optional, full or short, default short

      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: test
          scandir: assets